name: Test deployment

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
        # Review gh actions docs if you want to further define triggers, paths, etc
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
    test-deploy:
        name: Test deployment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: threeal/setup-yarn-action@v2.0.0

            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Test build website
              run: yarn build
